### ISSUE TITLE
Ids starting with digits are not converted

### ISSUE THREAD

**Issue by mementum** [asciidoctor/kramdown-asciidoc#115]
Version: 2.1.0
----

Good case

**Input**
```
# An Example {#x-01-x}
```
**Output**
```
[#x-01-x]
= An Example
```
----
Bad case

**Input**
```
# An Example {#01-x}
```
**Output**
```

= An Example {#01-x}
```

**Comment by mojavelinux** [comment]
Although not explicitly stated in the [docs for an explicit header ID](https://kramdown.gettalong.org/syntax.html#specifying-a-header-id), this is a restriction imposed by Kramdown. Since Kramdown AsciiDoc works with the parse tree provided by Kramdown, you'll need to file an issue in that project if you want to see a change. As it currently stands, the example you provided is not valid Kramdown markup.

**Comment by mementum** [comment]
Thanks for the feedback Dan.

**Comment by mojavelinux** [comment]
Btw, if this is changed in Kramdown, then Kramdown AsciiDoc will inherit that change.
