### ISSUE TITLE
Wrongly translated list continuation in nested lists

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/kramdown-asciidoc#118]
If you have the Markdown
```md
- foo
    - bar
        - baz

      bam
```
`bam` continues `bar`.

This currently is converted to the AsciiDoc
```adoc
* foo
 ** bar
  *** baz

+
bam
```
where `bam` continues `foo` instead.

It should instead be
```adoc
* foo
 ** bar
  *** baz

+
bam

+
{empty}
```
or the imho less nice
```adoc
* foo
 ** bar
+
--
  *** baz
--
+
bam
```

**Comment by mojavelinux** [comment]
Regarding this output:

```
* foo
 ** bar
  *** baz

+
bam
```

This is the correct result. The single empty line changes the attachment from baz to bar, which is what it should be doing based on the example you provided.

However, it appears that Asciidoctor is converting it incorrectly. The the issue is actually with Asciidoctor core (which is not too much of a surprise since list parsing in Asciidoctor is still very problematic).

> or the imho less nice

kramdown-asciidoc is not going to use open blocks to attach blocks to list items. It's too complex and breaks down if more than one level is needed.

**Comment by Vampire** [comment]
Oh, I see.
From what eskwayrd said on Zulip, I understood the opposite.
Can you move this issue to the `asciidoctor` repo then?
Of course Kramdoc should not be changed to adapt to an Asciidoctor bug.

**Comment by mojavelinux** [comment]
I would prefer if the issue were resubmitted since the description pertains to Kramdown AsciiDoc and thus would not transfer well.

**Comment by mojavelinux** [comment]
It turns out there is already an issue for this, and has been known for years. See https://github.com/asciidoctor/asciidoctor/issues/2353

In order to fix this, list parsing has to be rewritten in Asciidoctor. This is something we are studying in the AsciiDoc Language. Once we figure it out, the new parsing logic will be put into Asciidoctor.
