### ISSUE TITLE
Add support for multi-paragraph admonitions

### ISSUE THREAD

**Issue by simon-dew** [asciidoctor/kramdown-asciidoc#72]
I really appreciate the way that kramdown-asciidoc turns regular Markdown paragraphs into proper AsciiDoc admonitions, if they begin with a typical admonition marker such as *Note:*. In addition to this, I'd like a way of marking up a multi-paragraph admonition in Markdown, so that kramdown-asciidoc will convert it into a single AsciiDoc admonition block.

Possible markup: `!!!` as used in [python-markdown], [mkdocs]. This seems to have support on multiple platforms, but it doesn't degrade gracefully when using markdown processors that don't support this markup.

Another possible markup: `::: fenced_divs :::` as used in pandoc with the [fenced_divs] extension. Doesn't seem to be so widely recognized. Also doesn't degrade gracefully.

My preferred solution would be to recognize a blockquote `>` starting with any of the current admonition markers as an admonition. This degrades gracefully. It also has the advantage that it is compatible with the markdown output from [pandoc] -- useful for toolchain pipelines.

[python-markdown]: https://python-markdown.github.io/extensions/admonition/
[mkdocs]: https://squidfunk.github.io/mkdocs-material/extensions/admonition/
[fenced_divs]: https://pandoc.org/MANUAL.html#divs-and-spans
[pandoc]: https://pandoc.org

**Comment by mojavelinux** [comment]
This library is not a Markdown parser. We cannot add more features to Markdown in order to convert it. What we can do is take the Markdown parsed by Kramdown and convert it to AsciiDoc (hence the name, Kramdown AsciiDoc). Therefore, the syntax has to already be a Markdown syntax that Kramdown recognizes.

What we might be able to do is look ahead in the blockquote to see if there are more blocks and enclose the result in an AsciiDoc admonition.

```
> **Note**
> This is a note.
>
> This is more of that note.
```

Interesting, there is thread on the GitHub discussion forums about extending Markdown (again) to support multi-block admonitions. https://github.com/github-community/community/discussions/16925 But that's a long way from being supported by Kramdown.
