### ISSUE TITLE
question about attributes

### ISSUE THREAD

**Issue by jerCarre** [asciidoctor/kramdown-asciidoc#79]
Hello,

I want to use custom attributes in generated asciidoctor file.
So in md (not GFM) I define a Yaml Front Matter with my "custom-attribute" and in the body of the document I try to use it with the syntax {custom-attribute}.
but during kramdown-asciidoc conversion, {custom-attribute} becomes \{custom-attribute}, why ? and how can I change this ?

thx

**Comment by mojavelinux** [comment]
That's not how this converter works. That's because Markdown doesn't understand attribute references. The converter takes keys in the front matter and rewrites them as attribute entries in the AsciiDoc document header. You can then use those attribute references in the AsciiDoc document, but you need to add them **after** conversion to AsciiDoc.

In other words, given this Markdown:

```
---
key: value
---

# Title

content
```

It produces this AsciiDoc:

```
= Title
:key: value

content
```

You then then modify the AsciiDoc to use this attribute reference like so:

```
= Title
:key: value

The attribute named key is {key}.
```
